libreplan:
  build: .
  links:
    db: db
  ports: ["8888:8080"]

smtp:
  image: catatnight/postfix
  hostname: postfix
  environment:
    # You could change this to something more suitable
    - maildomain=kartoza.com
    - smtp_user=noreply:docker

db:
  image: kartoza/postgis
  volumes:
    - ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker
  volumes:
    - ./backups:/backups

dbbackups:
  image: kartoza/pg-backup
  hostname: pg-backups
  volumes:
    - ./backups:/backups
  links:
    - db:db
  environment:
    # take care to let the project name below match that
    # declared in the top of the makefile
    - DUMPPREFIX=PG_libreplan
    - PGUSER=libreplan
    - PGPASSWORD=libreplan
    - PGPORT=5432
    - PGHOST=db
    - PGDATABASE=libreplan
  volumes:
    - ./backups:/backups

